version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test

      - run:
          name: Install Vercel
          command: sudo npm i -g vercel
      
      - run:
          name: Run Vercel
          command: |
            URL=$(vercel --public -t PVsACss8tjYdHe6fDLqyVDHH --confirm)
            curl --silent -L $URL
